// Code generated by x. DO NOT EDIT.
// Code generated by x. DO NOT EDIT.
// Code generated by x. DO NOT EDIT.

package main

import (
	"github.com/obnahsgnaw/protocolhandler/cmd/cmd"
	"time"
)

func init() {
	time.Local = time.FixedZone("CST", 8*3600) // 东 8 区
}

func main() {
	cmd.Execute()
}
